channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - cmake==3.21.1
  - pip
  - Pillow
  - dlib
  - face_recognition
  - matplotlib
  - numpy
  - streamlit==0.85.1

  - pip:
    - mediapipe
    - streamlit-webrtc==0.6.3
    - opencv-contrib-python==4.5.3.56
    - opencv-python==4.5.3.56

