 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - Pillow
     - matplotlib
     - mediapipe
     - streamlit
     - streamlit-webrtc
     - opencv-python-headless
     - face_recognition
